# Config File for SimpleQuizzes
delay: 30 # How long to wait between questions in seconds
check-chat: true
messages: # %question%, %answer% and %player% placeholders are supported here.
  prefix: '&4[&2SimpleQuizzes&4]&r '
  new-question: '&6New Question: &b&l%question%'
  tip: "&eType &n'/quiz <answer>'&e to answer"
  answer: '&6The answer was &b&l%answer%&6.'
  correct-broadcast: '&a&l%player%&a has Answered Correctly! &6The answer was &b&l%answer%&6.'
  incorrect: '&4Wrong answer try again.'
  late: '&cSorry too late.'
questions:
  - question: "Whats 1+1?"
    answer: '2'
  - question: "Where is Microsoft's Headquarters?"
    answer: 'Redmond Washington'
rewards:
  - 'give %player% diamond 1'